{% set name = "drf-yasg" %}
{% set version = "1.20.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d50f197c7f02545d0b736df88c6d5cf874f8fea2507ad85ad7de6ae5bf2d9e5a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4
    - setuptools_scm
  run:
    - coreapi >=2.3.3
    - coreschema >=0.0.4
    - django >=1.11.7
    - djangorestframework >=3.8
    - inflection >=0.3.1
    - packaging
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4
    - ruamel.yaml >=0.15.34
    - six >=1.10.0
    - uritemplate >=3.0.0

test:
  imports:
    - drf_yasg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/axnsan12/drf-yasg
  summary: Automated generation of real Swagger/OpenAPI 2.0 schemas from Django Rest Framework code.
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - julian-belina
    - hadim
