{% set name = "drf-yasg" %}
{% set version = "1.21.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/drf-yasg-{{ version }}.tar.gz
  sha256: 4c3b93068b3dfca6969ab111155e4dd6f7b2d680b98778de8fd460b7837bdb0d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=40.6.3
    - wheel
    - setuptools-scm >=3.0.3
    - pip
  run:
    - python >=3.6
    - python-coreapi >=2.3.3
    - python-coreschema >=0.0.4
    - djangorestframework >=3.10.3
    - django >=2.2.16
    - ruamel.yaml >=0.16.13
    - inflection >=0.3.1
    - packaging >=21.0
    - pytz >=2021.1
    - uritemplate >=3.0.0

test:
  imports:
    - drf_yasg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/axnsan12/drf-yasg
  summary: Automated generation of real Swagger/OpenAPI 2.0 schemas from Django Rest Framework code.
  license: BSD-3-Clause
  license_file:
    - LICENSE.rst


extra:
  recipe-maintainers:
    - julian-belina
    - hadim
